name: ci
on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 18.x

      - uses: actions/cache@v2
        id: yarn-cache
        with:
          path: |
            ~/cache
            !~/cache/exclude
            **/node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install dependencies
        run: yarn install

      - name: Linting
        run: yarn lint

      - name: Test
        run: yarn test:ci

      - name: Build
        env:
          NEXT_PUBLIC_STRAPI_GRAPHQL_API: https://gamehub-api.leovdn.dev/graphql
          NEXT_PUBLIC_IMAGES_DOMAIN: https://gamehub-api.leovdn.dev
          NEXT_PUBLIC_API_URL: https://gamehub-api.leovdn.dev
        run: yarn build
